site_name: Sakurazaka
site_url: https://aki-192.github.io/sakura/
nav:
  - index.md
  - live.md
  - sokosaku.md
  - chokosaku.md
  - 3rdgen.md
  - yt-channel.md
  - misc.md
  - keyakake.md
theme:
  name: material
  palette:
    primary: custom
plugins: []
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_css:
  - stylesheets/extra.css